### ISSUE TITLE
lab5: Discrepancy between lab instruction and available data

### ISSUE THREAD

**Issue by VictorieeMan** [arvestad/da3018_vt2023_repo#7]
Not a huge problem. But I noticed that the [lab instructions](https://kurser.math.su.se/mod/page/view.php?id=81009) mentioned that the all_courses.txt contains 30000 lines:

_"The data set you will experiment with is a set of Stockholm University course names (not all of them actually exists). The different files simple have a different number of them. The file all_courses.txt contains 30000 lines."_

But the available repo file contains 10000 lines of data: [all_courses.txt](https://github.com/arvestad/da3018_vt2023_repo/blob/master/lab5/data/all_courses.txt)

I don't know if that matters, but I think it's good to have mentioned so that it does not confuse anyone debugging their code.

**Comment by arvestad** [comment]
Thanks, this has now been corrected in the lab text.
